# where data files will reside
dbpath=C:\Users\nateh\OneDrive\Documents\GitHub\JavaScript-Frameworks-Projects\MongoDB\db

# where the log file will be stored
logpath=C:\Users\nateh\OneDrive\Documents\GitHub\JavaScript-Frameworks-Projects\MongoDB\mongo-server.log

# how verbose the server will be logging
verbose=vvvvv